name: Links

on:
  pull_request:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Exclude Path
        run: |
          curl https://raw.githubusercontent.com/pingcap/docs/master/.lycheeignore --output .lycheeignore

      - name: Check Links
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          # Accept 429 for now due to github rate limit.
          # See https://github.com/lycheeverse/lychee/issues/634
          args: -E --exclude-mail -i -n -t 45 -- **/*.md *.md
          output: out.md
          jobSummary: false
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Check Failed Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          file-path: "./out.md"